---
# Source: external-secrets/templates/awssm-cluster-secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: awssm-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      role: "arn:aws:iam::065204381364:role/external-secrets"
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: &secretName awssm-secret
            namespace: &secretNamespace "external-secrets"
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: *secretName
            namespace: *secretNamespace
