external-secrets:
  certController:
    resources:
      limits:
        cpu: 0m
      requests:
        cpu: 0m
        memory: 0Mi
  resources:
    limits:
      cpu: 0m
    requests:
      cpu: 0m
      memory: 0Mi
  webhook:
    resources:
      limits:
        cpu: 0m
      requests:
        cpu: 0m
        memory: 0Mi
