---
# Source: external-secrets/charts/external-secrets/templates/servicemonitor.yaml
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
    helm.sh/chart: external-secrets-0.17.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.17.0"
    app.kubernetes.io/managed-by: Helm
    prometheus: cluster-monitoring
  name: external-secrets-metrics
  namespace: "external-secrets"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: external-secrets
  namespaceSelector:
    matchNames:
    - external-secrets
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 25s
    honorLabels: false
---
# Source: external-secrets/charts/external-secrets/templates/servicemonitor.yaml
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
    helm.sh/chart: external-secrets-0.17.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.17.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/metrics: "webhook"
    prometheus: cluster-monitoring
  name: external-secrets-webhook-metrics
  namespace: "external-secrets"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/metrics: "webhook"
  namespaceSelector:
    matchNames:
    - external-secrets
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 25s
    honorLabels: false
---
# Source: external-secrets/charts/external-secrets/templates/servicemonitor.yaml
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
    helm.sh/chart: external-secrets-0.17.0
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.17.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/metrics: "cert-controller"
    prometheus: cluster-monitoring
  name: external-secrets-cert-controller-metrics
  namespace: "external-secrets"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-cert-controller
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/metrics: "cert-controller"
  namespaceSelector:
    matchNames:
    - external-secrets
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 25s
    honorLabels: false
