{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1/ClusterSecretStore" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotaions:
    # ensure that create the cluster secrets store after external-secrets
    # operator with it's crds is rollout
    argocd.argoproj.io/sync-wave: "100"
  name: awssm-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      role: {{ .Values.aws.role | quote }}
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: &secretName awssm-secret
            namespace: &secretNamespace {{ .Release.Namespace | quote }}
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: *secretName
            namespace: *secretNamespace
{{- end }}
