{{- if (.Values.bootstrapResources).enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
data:
  aws_access_key_id: {{ required "A valid aws.accessKeyId is required to bootstrap!" .Values.aws.accessKeyId | b64enc }}
  aws_secret_access_key: {{ required "A valid aws.secretAccessKey is required to bootstrap!" .Values.aws.secretAccessKey | b64enc }}
{{- end }}
