{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1/ClusterSecretStore" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: awssm-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      role: {{ .Values.aws.role | quote }}
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: awssm-secret
            namespace: external-secrets
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: awssm-secret
            namespace: external-secrets
{{- end }}
