{{- if (.Values.bootstrapResources).enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
stringData:
  aws_access_key_id: {{ required "A valid aws.accessKeyId is required to bootstrap!" .Values.aws.accessKeyId | quote }}
  aws_secret_access_key: {{ required "A valid aws.secretAccessKey is required to bootstrap!" .Values.aws.secretAccessKey | quote }}
{{- end }}
